# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python

python: 
    - 2.7
    - 3.6

env:
    global:
        - TRAVIS_CK_WHICH_TEST=teleport
    matrix:
        - TRAVIS_CK_USE_PYTHON_SIM=1    TRAVIS_CK_CXX_COMPILER=llvm
        - TRAVIS_CK_USE_PYTHON_SIM=0    TRAVIS_CK_CXX_COMPILER=llvm
        - TRAVIS_CK_USE_PYTHON_SIM=0    TRAVIS_CK_CXX_COMPILER=gcc

matrix:
    include:
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=1  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=gcc
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=1  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=gcc

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew update                                                         # this swaps python versions and makes 3 the default one

            if [ "$TRAVIS_CK_CXX_COMPILER" == "llvm" ]; then
                brew install llvm\@5
                export TRAVIS_CK_COMPILER_CHOICE="Version 5"
            elif [ "$TRAVIS_CK_CXX_COMPILER" == "gcc" ]; then
                brew install gcc\@6 || brew link --overwrite gcc\@6             # to avoid symlink conflict with oclint
                export TRAVIS_CK_COMPILER_CHOICE="Version 6"
            fi

            export CK_PLATFORM_NAME="generic-macos "                            # used later by CK (note the trailing space to make the choice unique)
        else
            sudo apt-get update -qq
            sudo apt-get install python-pip
            export WANTED_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION                 # since Python is supported in Linux, get it from Travis
            export CK_PLATFORM_NAME="generic-linux "                            # used later by CK (note the trailing space to make the choice unique)
        fi

install:
    - CWD=`pwd`
    - THIS_REPO_NAME=`basename $CWD`
    - echo "os=${TRAVIS_OS_NAME}, python=${WANTED_PYTHON_VERSION}, python_sim=${TRAVIS_CK_USE_PYTHON_SIM}, compiler=${TRAVIS_CK_CXX_COMPILER}"
    - PYTHON_FOR_CK=python
    - which ${PYTHON_FOR_CK}
    - ${PYTHON_FOR_CK} --version
    - ${PYTHON_FOR_CK} -m pip show pip                                                    # which version of pip were we running?
    - ${PYTHON_FOR_CK} -m pip install --ignore-installed --verbose pip setuptools         # make sure pip is also up to date no matter what
    - ${PYTHON_FOR_CK} -m pip show pip                                                    # which version of pip are we running?
    - ${PYTHON_FOR_CK} -m pip install ck                                                  # CK kernel itself
    - ck pull repo:${THIS_REPO_NAME}                                            # trigger pulling dependent repositories
    - echo "$CK_PLATFORM_NAME" | ck detect platform.os --update_platform_init   # set the platform to generic-linux (1) or generic-macos (2)
    - echo | ck detect soft:compiler.python --default_selection="$WANTED_PYTHON_VERSION" --first_match
    - echo | ck detect soft:compiler.${TRAVIS_CK_CXX_COMPILER} --default_selection="$TRAVIS_CK_COMPILER_CHOICE" --first_match
    -          ck install package:lib-python-scipy                              # enforce installation to avoid detecting a wrong one
    -          ck install package:lib-projectq --env.USE_PYTHON_SIM=${TRAVIS_CK_USE_PYTHON_SIM}

script:
    - ck run program:projectq-demo --cmd_key=${TRAVIS_CK_WHICH_TEST}
