# After changing this file, check it on:
#   http://lint.travis-ci.org/

os: linux

language: python

python: 
    - 2.7
    - 3.6

env:
    global:
        - TRAVIS_CK_WHICH_TEST=teleport
    matrix:
        - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=1
        - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=0
        - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=1
        - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=0

before_install:
    - sudo apt-get install python-pip

matrix:
    include:
#
# ------------------------------- Python2 on MacOSX: ------------------------------------
#
        - os: osx
          language: generic
          python:   2.7
          env:
                - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=0
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python\@2 || brew link --overwrite python\@2   # install and link python2 and pip2 to /usr/local/bin
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
                - python -m pip install --ignore-installed --verbose pip setuptools # make sure pip is also up to date no matter what
                - brew install llvm\@5
        - os: osx
          language: generic
          python:   2.7
          env:
                - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=1
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python\@2 || brew link --overwrite python\@2   # install and link python2 and pip2 to /usr/local/bin
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
                - python -m pip install --ignore-installed --verbose pip setuptools # make sure pip is also up to date no matter what
                - brew install llvm\@5
        - os: osx
          language: generic
          python:   2.7
          env:
                - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=0
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python\@2 || brew link --overwrite python\@2   # install and link python2 and pip2 to /usr/local/bin
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
                - python -m pip install --ignore-installed --verbose pip setuptools # make sure pip is also up to date no matter what
                - brew install gcc\@6 || brew link --overwrite gcc\@6           # to avoid symlink conflict with oclint
        - os: osx
          language: generic
          python:   2.7
          env:
                - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=1
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python\@2 || brew link --overwrite python\@2   # install and link python2 and pip2 to /usr/local/bin
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
                - python -m pip install --ignore-installed --verbose pip setuptools # make sure pip is also up to date no matter what
                - brew install gcc\@6 || brew link --overwrite gcc\@6           # to avoid symlink conflict with oclint
#
# ------------------------------- Python3 on MacOSX: ------------------------------------
#
        - os: osx
          language: generic
          python:   3.6
          env:
                - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=0
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python                                         # install and link python3 and pip3 to /usr/local/bin
                - brew install llvm\@5
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
        - os: osx
          language: generic
          python:   3.6
          env:
                - TRAVIS_CK_CXX_COMPILER=llvm   TRAVIS_CK_USE_PYTHON_SIM=1
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python                                         # install and link python3 and pip3 to /usr/local/bin
                - brew install llvm\@5
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
        - os: osx
          language: generic
          python:   3.6
          env:
                - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=0
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python                                         # install and link python3 and pip3 to /usr/local/bin
                - brew install gcc\@6 || brew link --overwrite gcc\@6           # to avoid symlink conflict with oclint
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH
        - os: osx
          language: generic
          python:   3.6
          env:
                - TRAVIS_CK_CXX_COMPILER=gcc    TRAVIS_CK_USE_PYTHON_SIM=1
          before_install:
                - brew update                                                   # this swaps python versions and makes 3 the default one
                - brew reinstall python                                         # install and link python3 and pip3 to /usr/local/bin
                - brew install gcc\@6 || brew link --overwrite gcc\@6           # to avoid symlink conflict with oclint
                - export PATH=/usr/local/opt/python/libexec/bin:$PATH

install:
    - echo "os=${TRAVIS_OS_NAME}, python=${TRAVIS_PYTHON_VERSION}, compiler=${TRAVIS_CK_CXX_COMPILER}, python_sim=${TRAVIS_CK_USE_PYTHON_SIM}"
    - which python
    - python --version
    - if [ $TRAVIS_OS_NAME == "osx" ]; then export CK_PLATFORM_INDEX=2; else export CK_PLATFORM_INDEX=1; fi
    - python -m pip install -r requirements.txt                                 # ck kernel itself
    - ck pull repo:ck-projectq                                                  # trigger pulling dependent repositories
    - echo $CK_PLATFORM_INDEX | ck detect platform.os --update_platform_init    # set the platform to generic-linux (1) or generic-macos (2)
    -          ck detect soft:compiler.python --full_path=`which python`        # pick the one Travis has set for us in the PATH
    -          ck detect soft:compiler.${TRAVIS_CK_CXX_COMPILER}
    -          ck install package:lib-projectq --env.USE_PYTHON_SIM=${TRAVIS_CK_USE_PYTHON_SIM}

script:
    - ck run program:projectq-demo --cmd_key=${TRAVIS_CK_WHICH_TEST}
