# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python

python: 
    - 2.7
    - 3.6

env:
    global:
        - TRAVIS_CK_WHICH_TEST=teleport
    matrix:
        - TRAVIS_CK_USE_PYTHON_SIM=1    TRAVIS_CK_CXX_COMPILER=llvm
        - TRAVIS_CK_USE_PYTHON_SIM=0    TRAVIS_CK_CXX_COMPILER=llvm
        - TRAVIS_CK_USE_PYTHON_SIM=0    TRAVIS_CK_CXX_COMPILER=gcc

matrix:
    include:
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=1  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=gcc
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=1  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=llvm
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6  TRAVIS_CK_USE_PYTHON_SIM=0  TRAVIS_CK_CXX_COMPILER=gcc

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew update                                                         # this swaps python versions and makes 3 the default one

            if [ "$WANTED_PYTHON_VERSION" == "2.7" ]; then
                brew reinstall python\@2 || brew link --overwrite python\@2     # install and link python2 and pip2 to /usr/local/bin
            else
                brew reinstall python                                           # install and link python3 and pip3 to /usr/local/bin
            fi
            export PATH=/usr/local/opt/python/libexec/bin:$PATH

            if [ "$TRAVIS_CK_CXX_COMPILER" == "llvm" ]; then
                brew install llvm\@5
            elif [ "$TRAVIS_CK_CXX_COMPILER" == "gcc" ]; then
                brew install gcc\@6 || brew link --overwrite gcc\@6             # to avoid symlink conflict with oclint
            fi

            export CK_PLATFORM_INDEX=2                                          # used later by CK
        else
            sudo apt-get update -qq
            sudo apt-get install python-pip
            export WANTED_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION                 # since Python is supported in Linux, get it from Travis
            export CK_PLATFORM_INDEX=1                                          # used later by CK
        fi

install:
    - CWD=`pwd`
    - THIS_REPO_NAME=`basename $CWD`
    - echo "os=${TRAVIS_OS_NAME}, python=${WANTED_PYTHON_VERSION}, python_sim=${TRAVIS_CK_USE_PYTHON_SIM}, compiler=${TRAVIS_CK_CXX_COMPILER}"
    - which python
    - python --version
    - python -m pip show pip                                                    # which version of pip were we running?
    - python -m pip install --ignore-installed --verbose pip setuptools         # make sure pip is also up to date no matter what
    - python -m pip show pip                                                    # which version of pip are we running?
    - python -m pip install -r requirements.txt                                 # ck kernel itself
    - ck pull repo:${THIS_REPO_NAME}                                            # trigger pulling dependent repositories
    - echo $CK_PLATFORM_INDEX | ck detect platform.os --update_platform_init    # set the platform to generic-linux (1) or generic-macos (2)
    -          ck detect soft:compiler.python --full_path=`which python`        # pick the one Travis has set for us in the PATH
    -          ck detect soft:compiler.${TRAVIS_CK_CXX_COMPILER}
    -          ck install package:lib-projectq --env.USE_PYTHON_SIM=${TRAVIS_CK_USE_PYTHON_SIM}

script:
    - ck run program:projectq-demo --cmd_key=${TRAVIS_CK_WHICH_TEST}
